import { kgToUnit, type WeightUnit } from "@/src/lib/weight-unit";
import { completeJSON } from "@/src/services/llm";

// P3 of the progress redesign: the weekly analysis card body, generated by
// the LLM from the dashboard's own aggregates. The rule-based synthesis
// (utils/progress.ts ruleInsights) stays as the instant/offline fallback.

export type AIInsightAction = {
  label: string;
  type: "training" | "nutrition";
};

export type AIInsight = {
  summary: string;
  actions: AIInsightAction[];
};

/** Compact, numeric-only snapshot the dashboard already computes — the LLM
    never sees raw logs/meals, just aggregates. null = unknown/no data. */
export type WeeklyInsightStats = {
  goal: string | null; // lose_weight | gain_muscle | maintain
  week: { done: number; plan: number };
  lastWeek: { done: number; plan: number };
  streakWeeks: number;
  weekVolumeKg: number;
  volumeDeltaPct: number | null;
  /** true when volume/PRs come from logged sets, not plan estimates. */
  volumeIsReal: boolean;
  /** strongest logged lift by est. 1RM (kg), or null if nothing logged. */
  topPr: { name: string; e1rmKg: number } | null;
  avgKcal: number | null;
  kcalGoal: number | null;
  avgProteinG: number | null;
  proteinTargetG: number | null;
  weightKg: number | null;
  weightDelta30dKg: number | null;
  /** sets per muscle group, last 14 days, sorted desc */
  muscleSets: { group: string; sets: number }[];
  /** most neglected group (>=10 days untrained or <25% of top volume) */
  neglected: { group: string; days: number } | null;
};

function sanitize(raw: unknown): AIInsight {
  const obj = (raw ?? {}) as Record<string, unknown>;
  const summary = typeof obj.summary === "string" ? obj.summary.trim().slice(0, 400) : "";
  if (summary.length === 0) throw new Error("AI insight missing summary");

  const actions = (Array.isArray(obj.actions) ? obj.actions : [])
    .filter(
      (a): a is Record<string, unknown> =>
        a != null && typeof (a as Record<string, unknown>).label === "string",
    )
    .slice(0, 2)
    .map((a) => ({
      label: (a.label as string).trim().slice(0, 40),
      type: a.type === "nutrition" ? ("nutrition" as const) : ("training" as const),
    }))
    .filter((a) => a.label.length > 0);

  return { summary, actions };
}

export async function generateWeeklyInsight(
  stats: WeeklyInsightStats,
  language: string,
  unit: WeightUnit = "kg",
): Promise<AIInsight> {
  const languageName = language === "es" ? "Spanish" : "English";

  // Stats arrive in kg (storage unit); the payload speaks the user's unit so
  // the model never has to convert (and can't get it wrong).
  const w = (kg: number | null) =>
    kg == null ? null : Math.round(kgToUnit(kg, unit) * 10) / 10;
  const payload = {
    goal: stats.goal,
    week: stats.week,
    lastWeek: stats.lastWeek,
    streakWeeks: stats.streakWeeks,
    weightUnit: unit,
    weekVolume: Math.round(kgToUnit(stats.weekVolumeKg, unit)),
    volumeDeltaPct: stats.volumeDeltaPct,
    // "logged" volume is measured from real sets; "estimated" from the plan.
    volumeSource: stats.volumeIsReal ? "logged" : "estimated",
    topLift:
      stats.topPr != null
        ? { name: stats.topPr.name, estimated1RM: Math.round(kgToUnit(stats.topPr.e1rmKg, unit)) }
        : null,
    avgKcal: stats.avgKcal,
    kcalGoal: stats.kcalGoal,
    avgProteinG: stats.avgProteinG,
    proteinTargetG: stats.proteinTargetG,
    bodyWeight: w(stats.weightKg),
    bodyWeightDelta30d: w(stats.weightDelta30dKg),
    muscleSets: stats.muscleSets,
    neglected: stats.neglected,
  };

  const system = [
    "You are the user's personal fitness coach inside a training app, writing the weekly analysis card on their progress dashboard.",
    "Respond ONLY with strict JSON matching this schema:",
    '{"summary":string,"actions":[{"label":string,"type":"training"|"nutrition"}]}',
    "Rules:",
    "- summary: 2-3 sentences, max 55 words, plain text (no markdown, no emoji).",
    "- Address the user directly and informally.",
    "- Pick the ONE most important finding in the stats (missed sessions, protein gap, neglected muscle group, weight trend vs goal, volume drop) and lead with it, citing its concrete numbers.",
    "- End on a brief encouraging note grounded in something that went well (streak, volume up, adherence, a topLift PR).",
    "- volumeSource 'logged' = real logged sets (speak confidently about volume/PRs); 'estimated' = derived from the plan (don't cite it as an achieved number).",
    "- Only use numbers present in the stats; a null field is unknown — never mention or invent it.",
    `- units: weights in ${unit}, protein in g, energy in kcal. Weeks run Monday-Sunday; \`week\` is the current (partial) week.`,
    "- actions: 1-2 chips, imperative, max 4 words each; type reflects the domain.",
    `- Write summary and action labels in ${languageName}.`,
  ].join("\n");

  const parsed = await completeJSON(system, JSON.stringify(payload));
  return sanitize(parsed);
}
