-- Routine provenance. Three creation paths exist but only the coach one was
-- recorded (assigned_by): AI-generated and hand-made routines were
-- indistinguishable. `source` records it explicitly:
--   'user'  — created by the client in the app
--   'ai'    — generated by the in-app AI plan generator
--   'coach' — assigned through the admin panel
alter table public.routines
  add column if not exists source text not null default 'user'
    check (source in ('user', 'ai', 'coach'));

-- Backfill: coach rows are identifiable by assigned_by. Historic AI rows
-- can't be told apart from manual ones — they stay 'user'.
update public.routines set source = 'coach' where assigned_by is not null;

-- Keep the column honest without touching the admin panel: any writer that
-- sets assigned_by gets source forced to 'coach'.
create or replace function public.sync_routine_source()
returns trigger
language plpgsql
as $$
begin
  if new.assigned_by is not null then
    new.source := 'coach';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_routines_sync_source on public.routines;
create trigger trg_routines_sync_source
  before insert or update on public.routines
  for each row execute function public.sync_routine_source();
