-- ==========================================================================
-- Exercise demo GIFs: sets public.exercises.video_url to the gymvisual demo
-- hosted in the 'exercise-media' public Storage bucket. Generated from the
-- 258-exercise catalog -> GIF mapping (109 distinct GIFs; cue-only
-- variants share their movement's base demo). Matches on lower(name).
-- Re-runnable. Apply in the Supabase SQL editor.
-- ==========================================================================
begin;

update public.exercises e
   set video_url = v.url,
       updated_at = now()
  from (values
    ('Abdominales en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-crunch.gif'),
    ('Abdominales en Suelo (Crunch)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Abdominales Inversos (Reverse Crunch)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/reverse-crunch.gif'),
    ('Abducción de Cadera con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/resistance-band-seated-hip-abduction.gif'),
    ('Abductores en Polea (Cable Hip Abduction)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-hip-abduction.gif'),
    ('Aductores en Polea (Cable Hip Adduction)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-hip-adduction.gif'),
    ('Aperturas con Goma Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-fly.gif'),
    ('Aperturas con Mancuerna a 1 Brazo', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-fly.gif'),
    ('Aperturas en Banco Declinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-decline-fly.gif'),
    ('Aperturas en Banco Inclinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-incline-fly.gif'),
    ('Aperturas en Banco Plano', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-fly.gif'),
    ('Aperturas en Máquina (Peck Deck)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-fly.gif'),
    ('Bicicleta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/run.gif'),
    ('Burpee', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Burpees', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Cargada con Barra de Trampa (Hex Bar Carry)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-clean-and-press.gif'),
    ('Clean (Levantamiento)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-clean-and-press.gif'),
    ('Correr en la cinta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/run.gif'),
    ('Correr en lugar', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/run.gif'),
    ('Cruces en Polea Alta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-decline-fly.gif'),
    ('Cruces en Polea Baja', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-decline-fly.gif'),
    ('Cruces en Polea Media', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-decline-fly.gif'),
    ('Crunches', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Curl de bíceps', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Bíceps con Agarre Cruzado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Bíceps con Agarre Neutro (Martillo)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Bíceps con Agarre Prono (Inverso)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Bíceps con Barra Recta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Bíceps con Barra Z', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/ez-barbell-curl.gif'),
    ('Curl de Bíceps con Goma Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-concentration-curl.gif'),
    ('Curl de Bíceps con Mancuernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-biceps-curl.gif'),
    ('Curl de Bíceps en Banco Scott', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-preacher-curl.gif'),
    ('Curl de Bíceps en Inclinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-incline-curl.gif'),
    ('Curl de Bíceps en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-bicep-curl.gif'),
    ('Curl de Bíceps en Polea (Cable Curl)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-curl.gif'),
    ('Curl de Bíceps en Suspensión (TRX)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Curl de Femoral con Goma Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-lying-leg-curl.gif'),
    ('Curl de Femoral con Mancuerna (entre pies)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-lying-leg-curl.gif'),
    ('Curl de Femoral de Pie (Standing Leg Curl)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/standing-single-leg-curl.gif'),
    ('Curl de Femoral Sentado (Seated Leg Curl)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-leg-curl.gif'),
    ('Curl de Femoral Tumbado (Prone Leg Curl)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-lying-leg-curl.gif'),
    ('Curl de Femoral Unilateral (a 1 Pierna)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/standing-single-leg-curl.gif'),
    ('Curl de Muñeca con Barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-wrist-curl.gif'),
    ('Curl de Muñeca con Mancuerna', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-finger-curls.gif'),
    ('Curl de Muñeca Inverso', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-wrist-curl.gif'),
    ('Dead Bug', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Dips de Tríceps en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-dip.gif'),
    ('Dominadas con Agarre Abierto', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/wide-grip-pull-up.gif'),
    ('Dominadas con Agarre Cerrado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/close-grip-chin-up.gif'),
    ('Dominadas con Agarre Neutro', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Dominadas con Agarre Prono (Front)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Dominadas con Agarre Supino (Rear)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Dominadas con Bajada Lenta (Tempo)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Dominadas con Pausa en el Punto Superior', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Dominadas en Máquina Asistida', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-assisted-chin-up.gif'),
    ('Dragon Flag', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Elevación de Gemelos con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-single-leg-calf-raise.gif'),
    ('Elevación de Gemelos con Déficit', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-standing-calf-raise.gif'),
    ('Elevación de Gemelos de Pie (Standing Calf Raise)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-standing-calf-raise.gif'),
    ('Elevación de Gemelos de Pie a 1 Pierna', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-standing-calf-raise.gif'),
    ('Elevación de Gemelos en Prensa de Piernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Elevación de Gemelos Sentado (Seated Calf Raise)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-calf-raise.gif'),
    ('Elevación de Pierna Lateral (Side-Lying Leg Raise)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/burpee.gif'),
    ('Elevación de Piernas Colgado (Hanging Leg Raise)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-standing-crunch.gif'),
    ('Elevación de Piernas en Banco (Decline Leg Raise)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-standing-crunch.gif'),
    ('Elevaciones de bíceps', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-curl.gif'),
    ('Elevaciones de piernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-standing-crunch.gif'),
    ('Elevaciones de piernas en colgado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-standing-crunch.gif'),
    ('Elevaciones de rodillas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Elevaciones de talones', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-standing-calf-raise.gif'),
    ('Elevaciones Frontales (Deltoides Anterior)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-front-raise.gif'),
    ('Elevaciones laterales', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-lateral-raise.gif'),
    ('Elevaciones Laterales (Deltoides Medio)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-lateral-raise.gif'),
    ('Elevaciones Laterales con Rotación Externa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-lateral-raise.gif'),
    ('Elevaciones Laterales Inclinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-incline-rear-lateral-raise.gif'),
    ('Encogimientos de Hombros (Shrugs)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-shrug.gif'),
    ('Encogimientos Detrás de la Espalda', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-shrug.gif'),
    ('Encogimientos en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-shrug.gif'),
    ('Extensión de Cuádriceps con Bajada Lenta (Tempo)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-leg-extension.gif'),
    ('Extensión de Cuádriceps con Goma Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/resistance-band-leg-extension.gif'),
    ('Extensión de Cuádriceps con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-leg-extension.gif'),
    ('Extensión de Cuádriceps en Máquina Sentado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-leg-extension.gif'),
    ('Extensión de piernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-leg-extension.gif'),
    ('Extensiones de tríceps', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps a 1 Brazo en Polea', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps con Agarre Neutro', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps con Goma', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-side-triceps-extension.gif'),
    ('Extensiones de Tríceps en Banco Inclinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-incline-pushdown.gif'),
    ('Extensiones de Tríceps en Banco Plano (Skull Crusher)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-dip.gif'),
    ('Extensiones de Tríceps en Polea (Pushdown)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps en Polea Invertido', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Extensiones de Tríceps por Encima de la Cabeza', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Face Pull (Deltoides Posterior + Manguito)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-twisting-pull.gif'),
    ('Face Pull con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-twisting-pull.gif'),
    ('Face Pull con Rotación Externa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-twisting-pull.gif'),
    ('Farmer''s Walk', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/farmers-walk.gif'),
    ('Farmer''s Walk (sujeción)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/farmers-walk.gif'),
    ('Flexión de Dedos con Goma', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-wrist-curl.gif'),
    ('Flexiones de brazos', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Fondos Asistidos', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Fondos con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-side-triceps-extension.gif'),
    ('Fondos de tríceps', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Fondos en Anillas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Fondos en Banco (Tríceps)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Fondos en Paralelas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Giro con Cable (Cable Woodchop)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-kneeling-crunch.gif'),
    ('Giros Rusos (Russian Twist)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Glute Bridge (Puente de Glúteo en Suelo)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-glute-bridge.gif'),
    ('Glute Bridge Unilateral', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-glute-bridge.gif'),
    ('Good Morning con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Good Morning con Barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Good Morning con Barra Baja', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Good Morning con Mancuerna (Goblet Style)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Good Morning con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Good Morning con Piernas Separadas (Sumo Good Morning)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-good-morning.gif'),
    ('Hip Thrust con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/resistance-band-hip-thrusts-on-knees-female.gif'),
    ('Hip Thrust con Barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lying-lifting-on-hip.gif'),
    ('Hip Thrust con Mancuerna', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lying-lifting-on-hip.gif'),
    ('Hip Thrust con Pausa en el Punto Superior', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lying-lifting-on-hip.gif'),
    ('Hip Thrust en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lying-lifting-on-hip.gif'),
    ('Hip Thrust Unilateral', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lying-lifting-on-hip.gif'),
    ('Hiperextensiones a 45°', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/hyperextension.gif'),
    ('Hiperextensiones con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/hyperextension.gif'),
    ('Hiperextensiones en Banco (Back Extension)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/hyperextension.gif'),
    ('Hiperextensiones en Suelo (Superman)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/hyperextension.gif'),
    ('Hiperextensiones Unilateral (a 1 pierna)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/hyperextension.gif'),
    ('Jalones a 1 Brazo en Polea', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pulldown.gif'),
    ('Jalones al Pecho en Polea (Front)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pulldown.gif'),
    ('Jalones en Máquina (Lat Pulldown)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-front-pulldown.gif'),
    ('Jalones Tras Nuca en Polea', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pulldown.gif'),
    ('Kettlebell Swing', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/kettlebell-swing.gif'),
    ('L-Sit', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Máquina de Abductores (Abductor Machine)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-hip-abduction.gif'),
    ('Máquina de Aductores (Adductor Machine)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-seated-hip-adduction.gif'),
    ('Nordic Curl (Curl Nórdico)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-lying-leg-curl.gif'),
    ('Nordic Curl Asistido con Banda', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-lying-leg-curl.gif'),
    ('Pallof Press (Prensa Pallof)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Paseo del Granjero (Farmer''s Walk)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/farmers-walk.gif'),
    ('Paseo del Granjero Unilateral (Suitcase Walk)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-single-arm-overhead-carry.gif'),
    ('Patada de Glúteo en 4 Apoyos (Fire Hydrant)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-standing-hip-extension.gif'),
    ('Patada de Glúteo en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-donkey-calf-raise.gif'),
    ('Patada de Glúteo en Polea (Donkey Kick)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-kickback.gif'),
    ('Patada de Tríceps (Kickback)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Peso muerto', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto a 1 Pierna', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-single-leg-deadlift.gif'),
    ('Peso Muerto con Agarre Invertido (Snatch Grip)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso muerto con barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto con Barra de Trampa (Hex Bar DL)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto con Cadena o Banda', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-stiff-leg-deadlift.gif'),
    ('Peso Muerto con Kettlebell (Goblet DL)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso muerto con mancuernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-deadlift.gif'),
    ('Peso Muerto con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso muerto con piernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto con Piernas Extendidas (Romanian con déficit)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto con Piernas Rígidas (Stiff-Leg)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-stiff-leg-deadlift.gif'),
    ('Peso Muerto Convencional', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto Deficitario', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto desde Bloque (Rack Pull)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-deadlift.gif'),
    ('Peso Muerto Invertido (Deficit RDL)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-romanian-deadlift.gif'),
    ('Peso Muerto Rumano (RDL)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-romanian-deadlift.gif'),
    ('Peso Muerto Sumo', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-sumo-deadlift.gif'),
    ('Pistol Squat (Sentadilla a 1 Pierna)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/single-leg-squat-pistol-male.gif'),
    ('Plancha', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Plancha (Plank)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Plancha con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-bicycle-crunch.gif'),
    ('Prensa de hombros', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Prensa de piernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Prensa de Piernas con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Prensa de Piernas Horizontal', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Prensa de Piernas Inclinada (45°)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Prensa de Piernas Unilateral', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sled-45-leg-press.gif'),
    ('Press Arnold', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press de banca', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Banca con Agarre Abierto', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-wide-bench-press.gif'),
    ('Press de Banca con Agarre Cerrado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-close-grip-bench-press.gif'),
    ('Press de Banca con Bajada Lenta (Tempo 3-1-1)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Banca con Mancuerna en Rotación Neutra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-bench-press.gif'),
    ('Press de Banca con Pausa en Pecho', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Banca Declinado', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-decline-bench-press.gif'),
    ('Press de Banca en Máquina Guiada', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/smith-bench-press.gif'),
    ('Press de Banca en Suelo (Floor Press)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Banca Inclinado (45°)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-bench-press.gif'),
    ('Press de Banca Plano', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Banca Unilateral', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-press.gif'),
    ('Press de Hombro a 1 Brazo', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press de Hombro con Agarre Neutro', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press de Hombro con Bajada Detrás de la Cabeza', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press de Hombro con Mancuernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-arnold-press.gif'),
    ('Press de Hombro con Pausa en la Cabeza', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press de Hombro en Máquina', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-military-press.gif'),
    ('Press de hombros', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Press Militar (por encima de la cabeza)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-seated-behind-head-military-press.gif'),
    ('Pullover en Polea', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-lying-extension-pullover-with-rope-attachment.gif'),
    ('Remo a dos manos', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bent-over-row.gif'),
    ('Remo al Mentón (Upright Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-upright-row.gif'),
    ('Remo al Mentón con Agarre Ancho', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-wide-grip-upright-row.gif'),
    ('Remo al Mentón con Agarre Estrecho', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-upright-row.gif'),
    ('Remo con barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo con Barra de Trampa (Hex Bar Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo con Barra Z (agarre en pronación)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo con Mancuerna a 1 Mano (One-Arm Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-incline-row.gif'),
    ('Remo con Mancuerna a 2 Manos', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-incline-row.gif'),
    ('Remo en Máquina Convergente', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-high-row.gif'),
    ('Remo en Máquina Sentado (Cable Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-seated-row.gif'),
    ('Remo en Polea Baja con Agarre Abierto', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-seated-wide-grip-row.gif'),
    ('Remo en Polea Baja con Agarre Supino', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-seated-row.gif'),
    ('Remo Gironda (V-Bar Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bent-over-row.gif'),
    ('Remo Inclinado con Bajada Excéntrica Lenta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo Inclinado con Barra (Barbell Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo Inclinado con Barra en T (T-Bar Row)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Remo Inclinado con Pausa en el Pecho', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-incline-row.gif'),
    ('Rodillo de Muñeca (Wrist Roller)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-wrist-curl.gif'),
    ('Rueda Abdominal (Ab Wheel Rollout)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/crunch-floor.gif'),
    ('Russian twists', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-russian-twists-on-stability-ball.gif'),
    ('Saltos de Gemelos (Pliométricos)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lever-standing-calf-raise.gif'),
    ('Saltos de tijera', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/jack-jump-male.gif'),
    ('Sentadilla Búlgara (Búlgar Split Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/suspended-split-squat.gif'),
    ('Sentadilla Búlgara con Pausa', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadilla con Apoyo en Pared (Wall Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadilla con Bajada Lenta (Tempo 4-1-1)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadilla con Banda Elástica', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/band-squat.gif'),
    ('Sentadilla con Barra de Trampa (Hex Bar Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-squat.gif'),
    ('Sentadilla con Cadenas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadilla con Mancuernas a los Lados', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-squat.gif'),
    ('Sentadilla con Pausa en el Punto Bajo', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadilla con Pierna Adelantada (Split Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/suspended-split-squat.gif'),
    ('Sentadilla con Salto (Jump Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/jump-squat.gif'),
    ('Sentadilla en Máquina Hack', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-hack-squat.gif'),
    ('Sentadilla en Máquina Multipower', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/smith-squat.gif'),
    ('Sentadilla en Máquina Smith', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/smith-squat.gif'),
    ('Sentadilla Frontal', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-front-squat.gif'),
    ('Sentadilla Goblet (Copa)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-goblet-squat.gif'),
    ('Sentadilla Sissy (Sissy Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sissy-squat.gif'),
    ('Sentadilla Trasera con Barra Alta', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-squat.gif'),
    ('Sentadilla Trasera con Barra Baja', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-squat.gif'),
    ('Sentadilla Zercher', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-zercher-squat.gif'),
    ('Sentadillas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Sentadillas con barra', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-bench-squat.gif'),
    ('Sentadillas con mancuernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-squat.gif'),
    ('Sissy Squat (Sentadilla Sissy)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/sissy-squat.gif'),
    ('Snatch (Arrancada)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-clean-and-press.gif'),
    ('Step-up con Mancuerna', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-step-up.gif'),
    ('Suitcase Carry (Carga Maletero)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/farmers-walk.gif'),
    ('Sujeción con Pinza (Plate Pinch)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/farmers-walk.gif'),
    ('Thruster (Sentadilla + Press)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-full-squat.gif'),
    ('Tríceps con cuerda', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/cable-pushdown.gif'),
    ('Tríceps con mancuernas', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-decline-triceps-extension.gif'),
    ('Vuelos Posteriores (Deltoides Posterior)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/dumbbell-lateral-raise.gif'),
    ('Zancada Caminando (Walking Lunge)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/walking-lunge.gif'),
    ('Zancada con Desplazamiento Lateral (Skater Squat)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada con Giro de Tronco', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada con Pausa en el Punto Bajo', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada con Pierna Elevada Trasera (Búlgaro)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada con Salto (Jump Lunge)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/lunge-with-jump.gif'),
    ('Zancada Cruzada (Curtsy Lunge)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada Hacia Atrás (Reverse Lunge)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif'),
    ('Zancada Lateral (Side Lunge)', 'https://rzgwkwxskrovxnnymxqo.supabase.co/storage/v1/object/public/exercise-media/barbell-lunge.gif')
  ) as v(name, url)
 where lower(e.name) = lower(v.name);

commit;

-- Verify (expect ~258 set, 0 nulls among catalog names):
-- select count(*) filter (where video_url is not null) as with_video,
--        count(*) filter (where video_url is null)     as without_video
-- from public.exercises;
